import pygame

WIN_WIDTH = 1920
WIN_HEIGHT = 1080

PLAYER_SIZE = 40

# Maze dimensions
PLAYER_SPEED = 6
CELL_SIZE = PLAYER_SIZE * 6  # Corridor size is 3x player size
WALL_THICKNESS = 3
COLS = 20  # Number of columns in the maze
ROWS = 30  # Number of rows in the maze

# Calculate total world size
WORLD_WIDTH = COLS * CELL_SIZE
WORLD_HEIGHT = ROWS * CELL_SIZE

FOV_ANGLE_DEGREES = 60
RAY_COUNT = 60
RAY_LENGTH = 300
# AURA_RADIUS = 50

LIGHT_AURA_RADIUS = 100
FLASHLIGHT_BASE_BRIGHTNESS = (40, 40, 40)
FLASHLIGHT_GRADIENT_STEPS = 8
FLASHLIGHT_MAX_BRIGHTNESS = (120, 120, 120)

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)         # Exit
START_BLUE = (0, 0, 255)  # Start
PURPLE = (40, 0, 80)      # Floor
PLAYER_COLOR = (255, 100, 100) # Player

# --- Shotgun Constants ---
SHOTGUN_AMMO_CAPACITY = 6
SHOTGUN_RELOAD_TIME = 2000 # in milliseconds
SHOTGUN_PELLET_COUNT = 8
SHOTGUN_SPREAD_ANGLE = 15 # degrees
SHOTGUN_RANGE = 400
SHOTGUN_PELLET_COLOR = (255, 200, 0)
SHOTGUN_PELLET_LIFETIME = 100 # ms

# --- Keybinds ---
SWAP_KEY = pygame.K_q
RELOAD_KEY = pygame.K_r